mutation {
  signup(
    firstName: "John"
    lastName: "Smith"
    age: 26
    email: "john@test.com"
    phone: "123-456-7890"
    password: "123456"
    address: {
      street1: "123 Test Street"
      city: "Jackson"
      state: "MS"
      zipcode: "39203"
    }
  ) {
    id
    firstName
    lastName
    age
    email
    phone
    age
    address {
      street1
      street2
      city
      state
      zipcode
    }
  }
}

mutation {
  login(email: "john@test.com", password: "123456")
}

mutation {
  updateRecipientProfile(allowPhoneContact: false) {
    id
    allowPhoneContact
    allowEmailContact
    location {
      lat
      lng
    }
  }
}

# Create Travel Service
mutation {
  createService(
    title: "Test travel with address"
    serviceType: TRAVEL
    notes: "Testing..."
    location: { address: "Test Address", lng: -88.426430, lat: 33.515996 }
    date: "2019-03-02T02:00:00+00:00"
    travelServiceDetails: {
      toLocation: { address: "Test TO address", lng: -88, lat: 33 }
      fromLocation: {
        address: "Test FROM address"
        lng: -88.426430
        lat: 33.515996
      }
    }
  ) {
    id
    title
    serviceType
    notes
    location {
      lat
      lng
    }
    date
  }
}

# Create Childcare Need
mutation {
  createNeed(
    title: "Babysitter Friday Night"
    needType: CHILDCARE
    notes: "No allergies"
    location: { lng: -88.426430, lat: 33.515996 }
    date: "2019-03-02T02:00:00+00:00"
    childcareNeedDetails: { age: [INFANT, TODDLER] }
  ) {
    id
    title
    needType
    notes
    location {
      lat
      lng
    }
    date
  }
}

mutation {
  createRecipientProfile(
    allowPhoneContact: true
    allowEmailContact: false
    location: {
      address: "100 Test Street, Starkville, MS"
      lng: -88.426430
      lat: 33.515996
    }
  ) {
    id
    allowEmailContact
    allowPhoneContact
    location {
      lat
      lng
    }
  }
}

# Create Lawncare Service
mutation {
  createLawncareService(
    equipmentNeeded: true
    description: "Cut my grass. I have a small yard."
    serviceId: "5c5b0509eb52da189e562eb0"
  ) {
    id
    equipmentNeeded
    description
  }
}

mutation AssignVolunteer($serviceId: ID!, $volunteerId: ID!) {
  assignVolunteer(serviceId: $serviceId, volunteerId: $volunteerId) {
    id
    title
  }
}
