fragment NeedDetails on Need {
  NeedDetails {
    ... on ChildcareNeed {
      id
      age
    }
  }
}

query Users {
  users {
    id
    fullName
  }
}

query Needs {
  needs(location: { lng: -88.813037, lat: 33.452127 }, range: 24) {
    id
    title
    location {
      lat
      lng
    }
    needType
    ...NeedDetails
    recipient {
      id
      fullName
    }
    volunteer {
      id
      fullName
    }
  }
}

query Me {
  me {
    id
    fullName
    avatar
    recipientProfile {
      id
      allowPhoneContact
      allowEmailContact
      location {
        lat
        lng
      }
    }
    requestedNeeds {
      id
      title
      needType
    }
  }
}

mutation {
  createRequest(
    need: "5ca3921448979e215e8fb36c"
    volunteer: "5c48cea7bfdf112e82c5b0df"
  ) {
    id
    need {
      id
      title
    }
    volunteer {
      id
      fullName
    }
    recipient {
      id
      fullName
    }
  }
}

query Requests {
  requests(userId: "5c48cea7bfdf112e82c5b0df") {
    id
    status
    need {
      id
      title
    }
    volunteer {
      id
      fullName
    }
    recipient {
      id
      fullName
    }
  }
}
