fragment ServiceDetails on Service {
  serviceDetails {
    ... on ChildcareService {
      id
      age
    }
    ... on TravelService {
      id
      fromLocation {
        address
        lat
        lng
      }
      toLocation {
        address
        lat
        lng
      }
    }
  }
}

query Users {
  users {
    id
    fullName
  }
}

query Services {
  services(location: { lng: -88.813037, lat: 33.452127 }, range: 24) {
    id
    title
    location {
      lat
      lng
    }
    serviceType
    ...ServiceDetails
    recipient {
      id
      fullName
    }
    volunteer {
      id
      fullName
    }
  }
}

query Me {
  me {
    id
    fullName
    avatar
    recipientProfile {
      id
      allowPhoneContact
      allowEmailContact
      location {
        lat
        lng
      }
    }
    requestedServices {
      id
      title
      serviceType
    }
  }
}
